import React,{useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import type {InterviewKit,InterviewQuestion,JobPreparation} from '../../types';
import {generateInterview,getInterviewKit,getPreparation,saveInterviewKit} from '../../services/preparations';

const labels:Record<InterviewQuestion['category'],string>={role:'岗位高频',experience:'经历深挖',gap:'差距与风险',scenario:'情景与专业题',reverse:'反问面试官'};
const basis=(item:JobPreparation)=>`${item.revision}:${JSON.stringify(item.document).length}:${item.matchResultSnapshot&&JSON.stringify(item.matchResultSnapshot).length}`;

export const InterviewPreparationView:React.FC=()=>{const{id=''}=useParams();const[item,setItem]=useState<JobPreparation|null>(null);const[kit,setKit]=useState<InterviewKit|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState('');const[selectedCategory,setSelectedCategory]=useState<InterviewQuestion['category']>('role');const navigate=useNavigate();
  useEffect(()=>{Promise.all([getPreparation(id),getInterviewKit(id)]).then(([prep,current])=>{setItem(prep);setKit(current);}).catch(error=>setError(error instanceof Error?error.message:'读取失败')).finally(()=>setLoading(false));},[id]);
  const questions=useMemo(()=>kit?.questions.filter(q=>q.category===selectedCategory)||[],[kit,selectedCategory]);const stale=!!item&&!!kit&&kit.generationBasisHash!==basis(item);
  const generate=async()=>{if(!item)return;setWorking(true);setError('');try{const fresh=await generateInterview(item);const protectedQuestions=(kit?.questions||[]).filter(q=>q.starred||q.answerNote.trim());const nextQuestions=[...protectedQuestions,...fresh.filter(next=>!protectedQuestions.some(old=>old.question===next.question))];const saved=await saveInterviewKit({preparationId:item.id,questions:nextQuestions,generationBasisHash:basis(item),createdAt:kit?.createdAt});setKit(saved);}catch(error){setError(error instanceof Error?error.message:'生成失败');}finally{setWorking(false);}};
  const update=async(id:string,updates:Partial<InterviewQuestion>)=>{if(!kit)return;const next={...kit,questions:kit.questions.map(q=>q.id===id?{...q,...updates}:q)};setKit(next);try{setKit(await saveInterviewKit(next));}catch(error){setError(error instanceof Error?error.message:'保存答题笔记失败');}};
  if(loading)return <div className="page-shell text-ink-secondary">正在打开面试准备...</div>;if(!item)return <div className="page-shell">{error||'求职准备不存在'}</div>;
  return <div className="page-shell max-w-6xl animate-fade-in"><header className="flex flex-wrap items-start justify-between gap-5 border-b border-line pb-6"><div><button onClick={()=>navigate('/preparations')} className="btn-link">← 我的求职准备</button><h1 className="mt-3 text-3xl">{item.name}</h1><p className="mt-2 text-sm text-ink-secondary">面试准备是私人内容，不会出现在公开主页。</p></div><button onClick={()=>void generate()} disabled={working} className="btn-primary">{working?'正在生成问题…':kit?'补充生成问题':'生成面试问题'}</button></header><div className="prep-tabs px-0"><Link to={`/preparations/${item.id}/home`}>求职主页</Link><Link className="active" to={`/preparations/${item.id}/interview`}>面试准备 <small>私人</small></Link></div>
  {stale&&<div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">求职主页内容已有更新。点击“补充生成问题”获取新问题；已收藏或已作答的问题会保留。</div>}{error&&<div className="mt-5 rounded-lg border border-terra-border bg-terra-light p-4 text-sm text-terra">{error}</div>}
  {!kit?.questions.length?<div className="card mt-6 py-20 text-center"><div className="text-4xl">◎</div><h2 className="mt-4 text-xl">从真实经历出发准备面试</h2><p className="mx-auto mt-2 max-w-lg text-sm text-ink-secondary">AI 会结合求职方向、主页内容和岗位差距，生成五类问题。不会替你编造答案。</p></div>:<div className="mt-6 grid gap-6 md:grid-cols-[220px_1fr]"><aside className="card h-fit p-3">{(Object.keys(labels) as InterviewQuestion['category'][]).map(category=><button key={category} onClick={()=>setSelectedCategory(category)} className={`flex w-full justify-between rounded-lg px-4 py-3 text-left text-sm ${selectedCategory===category?'bg-terra-light text-terra':'hover:bg-canvas'}`}><span>{labels[category]}</span><small>{kit.questions.filter(q=>q.category===category).length}</small></button>)}</aside><section className="space-y-4">{questions.map((question,index)=><article className="card" key={question.id}><div className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-terra-light text-xs font-semibold text-terra">{index+1}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h2 className="text-lg leading-relaxed">{question.question}</h2><button onClick={()=>void update(question.id,{starred:!question.starred})} aria-label={question.starred?'取消收藏':'收藏问题'} className={`text-xl ${question.starred?'text-amber-500':'text-ink-weak'}`}>{question.starred?'★':'☆'}</button></div><p className="mt-2 text-xs text-ink-secondary">为什么问：{question.rationale||'考察与岗位相关的思考和经历'}</p><label className="mt-5 block"><span className="label">我的答题笔记</span><textarea className="textarea h-32" value={question.answerNote} onChange={event=>setKit(current=>current?{...current,questions:current.questions.map(q=>q.id===question.id?{...q,answerNote:event.target.value}:q)}:current)} onBlur={event=>void update(question.id,{answerNote:event.target.value})} placeholder="记录事实、案例和关键数据，不需要一次写完…"/></label></div></div></article>)}</section></div>}
  </div>;
};
export default InterviewPreparationView;
