import React,{useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {isMatchResultV2,type PreparationMode} from '../../types';
import {buildSuggestions,createPreparation,generatePortfolio} from '../../services/preparations';
import {hasApiKey,loadResumes,loadSavedJobs,saveResume,type ResumeItem,type SavedJob} from '../../utils/storage';
import {parseResumeFile,readFileAsDataUrl} from '../../services/api';

export const NewPreparationView:React.FC<{onNeedApiKey:()=>void}>=({onNeedApiKey})=>{const[params]=useSearchParams();const jobs=loadSavedJobs();const[resumes,setResumes]=useState(loadResumes());const[mode,setMode]=useState<PreparationMode>(params.get('jobId')?'targeted':'targeted');const[selectedJob,setSelectedJob]=useState(params.get('jobId')||'');const[selectedResume,setSelectedResume]=useState('');const[direction,setDirection]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const navigate=useNavigate();
  const upload=async(file?:File)=>{if(!file)return;if(!hasApiKey()){onNeedApiKey();return;}setLoading(true);setError('');try{const parsed=await parseResumeFile(file);const sourceFileData=await readFileAsDataUrl(file);const item=saveResume(parsed,{name:file.name.replace(/\.pdf$/i,''),fileName:file.name,sourceFileData,sourceMimeType:file.type,makeCurrent:false});setResumes(loadResumes());setSelectedResume(item.id);}catch(error){setError(error instanceof Error?error.message:'简历解析失败');}finally{setLoading(false);}};
  const create=async()=>{if(!hasApiKey()){onNeedApiKey();return;}let job:SavedJob|undefined;let resumeItem:ResumeItem|undefined;let targetDirection=direction.trim();if(mode==='targeted'){job=jobs.find(item=>item.id===selectedJob);if(!job?.resumeSnapshot){setError('这条岗位没有保存分析简历，请先重新分析。');return;}if(job.scoringVersion==='radar-v2'&&!isMatchResultV2(job.matchResult)){setError('这条 radar-v2 岗位记录不完整，请返回“我的岗位投递”重新分析后再创建。');return;}targetDirection=job.intendedPosition||job.jd.position||job.jobName||'目标岗位';}else{resumeItem=resumes.find(item=>item.id===selectedResume);if(!targetDirection||!resumeItem){setError('请填写求职方向并选择一份简历。');return;}}
    const sourceResume=job?.resumeSnapshot||resumeItem!.resume;setLoading(true);setError('');try{const document=await generatePortfolio('new',{resume:sourceResume,direction:targetDirection,jobDescription:job?.jd,matchResult:job?.matchResult});const item=await createPreparation({mode,name:mode==='targeted'?`${targetDirection}${job?.company||job?.jd.company?` @ ${job?.company||job?.jd.company}`:''}`:`${targetDirection} · 通用主页`,careerDirection:targetDirection,sourceJobId:job?.id,sourceResumeId:job?.analyzedResumeId||resumeItem?.id,sourceResumeVersion:job?.analyzedResumeVersion||resumeItem?.version,sourceResumeSnapshot:sourceResume,jobSnapshot:job?.jd,matchResultSnapshot:job?.matchResult,document,documentSchemaVersion:1,contentSuggestions:buildSuggestions(job),themeId:'clean-professional',themeConfig:{}});navigate(`/preparations/${item.id}/home`,{replace:true});}catch(error){setError(error instanceof Error?error.message:'创建失败');}finally{setLoading(false);}};
  return <div className="page-shell max-w-5xl animate-fade-in"><button onClick={()=>navigate('/preparations')} className="btn-link mb-5">← 返回我的求职准备</button><header className="page-header"><div><p className="eyebrow">CREATE PORTFOLIO</p><h1>新建求职准备</h1><p className="page-subtitle">选择生成依据，AI 只会提炼你已经提供的真实经历。</p></div></header>
  <div className="mb-6 grid gap-4 md:grid-cols-2"><button onClick={()=>setMode('targeted')} className={`card text-left transition ${mode==='targeted'?'border-terra ring-2 ring-terra/10':'hover:border-terra/50'}`}><strong className="text-lg">针对岗位创建</strong><p className="mt-2 text-sm text-ink-secondary">使用已有岗位分析、当时的简历快照和差距结果。</p></button><button onClick={()=>setMode('general')} className={`card text-left transition ${mode==='general'?'border-terra ring-2 ring-terra/10':'hover:border-terra/50'}`}><strong className="text-lg">创建通用求职主页</strong><p className="mt-2 text-sm text-ink-secondary">选择简历并填写求职方向，不重复进行岗位分析。</p></button></div>
  <section className="card">{mode==='targeted'?<><h2 className="text-lg">选择岗位分析记录</h2><div className="mt-5 max-h-[430px] space-y-3 overflow-y-auto">{jobs.map(job=>{const chosen=selectedJob===job.id;const incomplete=job.scoringVersion==='radar-v2'&&!isMatchResultV2(job.matchResult);return <button key={job.id} disabled={incomplete} onClick={()=>setSelectedJob(job.id)} className={`w-full rounded-lg border p-4 text-left ${incomplete?'cursor-not-allowed border-line bg-canvas opacity-60':chosen?'border-terra bg-terra-light':'border-line hover:border-terra/50'}`}><div className="flex justify-between gap-4"><div><strong>{job.jobName||job.jd.position||'未命名岗位'}</strong><p className="mt-1 text-xs text-ink-secondary">{job.company||job.jd.company||'未注明公司'} · 使用分析时的简历版本 {job.analyzedResumeVersion||'—'}</p>{incomplete&&<p className="mt-1 text-xs text-terra">新版分析记录不完整，需先重新分析</p>}</div><span className="text-sm text-terra">{incomplete?'需重新分析':`${job.matchScore??job.matchResult.score??'—'} 分`}</span></div></button>})}{jobs.length===0&&<div className="py-10 text-center text-sm text-ink-secondary">还没有岗位分析记录。<button onClick={()=>navigate('/jobs')} className="ml-1 text-terra">先去新增岗位分析</button></div>}</div></>:<><h2 className="text-lg">通用主页信息</h2><label className="mt-5 block"><span className="label">求职方向</span><input className="input" value={direction} onChange={event=>setDirection(event.target.value)} placeholder="例如：B 端产品经理"/></label><div className="mt-6 flex items-center justify-between"><span className="label">选择已有简历</span><label className="btn-ghost h-8 cursor-pointer px-3 text-xs">上传新 PDF<input type="file" accept=".pdf,application/pdf" className="hidden" onChange={event=>void upload(event.target.files?.[0])}/></label></div><div className="mt-2 space-y-2">{resumes.map(item=><button key={item.id} onClick={()=>setSelectedResume(item.id)} className={`w-full rounded-lg border p-3 text-left ${selectedResume===item.id?'border-terra bg-terra-light':'border-line'}`}><strong className="text-sm">{item.name}</strong><span className="ml-2 text-[11px] text-ink-weak">{item.type==='original'?'原始简历':'定制简历'} · V{item.version}</span></button>)}</div></>}</section>
  {error&&<div className="mt-4 rounded-lg border border-terra-border bg-terra-light p-3 text-sm text-terra">{error}</div>}<div className="mt-6 flex justify-end"><button onClick={()=>void create()} disabled={loading||(mode==='targeted'?!selectedJob:!selectedResume||!direction.trim())} className="btn-primary min-w-40">{loading?'AI 正在生成...':'生成求职主页'}</button></div></div>;
};
export default NewPreparationView;
