import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import type {ContentSuggestion,JobPreparation,PortfolioBlock,PortfolioBlockType,ThemeId} from '../../types';
import PortfolioRenderer from '../PortfolioRenderer';
import {getPreparation,optimizeBlock,proposeSupplement,publishPreparation,themeNames,trackPreparationWrite,unpublishPreparation,updatePreparation} from '../../services/preparations';
import {formatFollowUpExperience} from '../../services/api';
import {generateId,loadResumes,replaceResumeData} from '../../utils/storage';

type Proposal={blockId:string;before:Record<string,unknown>;beforeHash:string;after:Record<string,unknown>;explanation:string;suggestionId?:string;userFacts?:string;syncLibrary?:boolean};
const blockNames:Record<PortfolioBlockType,string>={hero:'个人定位',advantages:'核心优势',projects:'项目经历',experience:'工作经历',skills:'专业技能',education:'教育背景',contact:'联系方式'};
const blockTypes:PortfolioBlockType[]=['advantages','projects','experience','skills','education','contact'];
const arr=(value:unknown):any[]=>Array.isArray(value)?value:[];
const contentHash=(value:unknown)=>{const source=JSON.stringify(value);let hash=2166136261;for(let index=0;index<source.length;index+=1){hash^=source.charCodeAt(index);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');};

export const PreparationEditorView:React.FC=()=>{const{id=''}=useParams();const navigate=useNavigate();const[item,setItem]=useState<JobPreparation|null>(null);const[selectedId,setSelectedId]=useState('');const[loading,setLoading]=useState(true);const[dirty,setDirty]=useState(false);const[flushRequested,setFlushRequested]=useState(false);const[saveState,setSaveState]=useState<'saved'|'saving'|'offline'|'conflict'>('saved');const[error,setError]=useState('');const[instruction,setInstruction]=useState('突出与目标方向相关的行动和结果');const[working,setWorking]=useState(false);const[proposal,setProposal]=useState<Proposal|null>(null);const[activeSuggestion,setActiveSuggestion]=useState<ContentSuggestion|null>(null);const[userFacts,setUserFacts]=useState('');const[targetBlockId,setTargetBlockId]=useState('');const[syncLibrary,setSyncLibrary]=useState(false);const loaded=useRef(false);const editVersion=useRef(0);
  const recoveryKey=`wf_preparation_draft:${localStorage.getItem('wf_cloud_user_id')||'local'}:${id}`;
  useEffect(()=>{getPreparation(id).then(value=>{const recovery=localStorage.getItem(recoveryKey);let next=value;if(recovery){try{const parsed=JSON.parse(recovery);if(parsed.revision===value.revision&&parsed.savedAt>value.updatedAt)next={...value,document:parsed.document,contentSuggestions:parsed.contentSuggestions,themeId:parsed.themeId};else if(parsed.revision!==value.revision){next={...value,document:parsed.document,contentSuggestions:parsed.contentSuggestions,themeId:parsed.themeId};setSaveState('conflict');setError('发现未同步的本机草稿和更新的云端版本，请选择要保留的版本。');}}catch{/* ignore */}}setItem(next);setSelectedId(next.document.blocks[0]?.id||'');loaded.current=true;}).catch(err=>setError(err instanceof Error?err.message:'读取失败')).finally(()=>setLoading(false));},[id,recoveryKey]);
  useEffect(()=>{if(!item||!dirty||!loaded.current)return;localStorage.setItem(recoveryKey,JSON.stringify({revision:item.revision,document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,savedAt:new Date().toISOString()}));const timer=window.setTimeout(async()=>{const savingVersion=editVersion.current;setSaveState('saving');setFlushRequested(false);try{const saved=await trackPreparationWrite(updatePreparation(item,{document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,themeConfig:item.themeConfig}));if(editVersion.current===savingVersion){setItem(saved);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);}else{setItem(current=>current?{...current,revision:saved.revision,updatedAt:saved.updatedAt}:current);setSaveState('saving');}}catch(error){const message=error instanceof Error?error.message:'';setSaveState(message.includes('其他页面')?'conflict':'offline');setError(message||'保存失败');}},flushRequested?0:800);return()=>window.clearTimeout(timer);},[dirty,item,recoveryKey,flushRequested]);
  useEffect(()=>{const flush=()=>setFlushRequested(true);window.addEventListener('wf-flush-preparations',flush);return()=>window.removeEventListener('wf-flush-preparations',flush);},[]);
  const blocks=useMemo(()=>[...(item?.document.blocks||[])].sort((a,b)=>a.order-b.order),[item]);const selected=blocks.find(block=>block.id===selectedId)||blocks[0];
  const change=(mutate:(draft:JobPreparation)=>JobPreparation)=>{editVersion.current+=1;setItem(current=>current?mutate(current):current);setDirty(true);};
  const changeIdentity=(key:'name'|'headline'|'tagline'|'location',value:string)=>change(current=>({...current,document:{...current.document,identity:{...current.document.identity,[key]:value}}}));
  const changeBlock=(id:string,updates:Partial<PortfolioBlock>)=>change(current=>({...current,document:{...current.document,blocks:current.document.blocks.map(block=>block.id===id?{...block,...updates}:block)}}));
  const readyForServerAction=()=>{if(dirty||saveState!=='saved'){setError('请等待当前草稿保存完成后再继续。');return false;}return true;};
  const move=(block:PortfolioBlock,delta:number)=>{const sorted=[...blocks];const index=sorted.findIndex(item=>item.id===block.id);const other=sorted[index+delta];if(!other)return;changeBlock(block.id,{order:other.order});changeBlock(other.id,{order:block.order});};
  const addBlock=(type:PortfolioBlockType)=>{const block:PortfolioBlock={id:`block_${Date.now()}`,type,title:blockNames[type],visible:true,order:blocks.length,data:type==='advantages'?{items:[]}:type==='skills'?{groups:[]}:{items:[]},sourceRefs:[]};change(current=>({...current,document:{...current.document,blocks:[...current.document.blocks,block]}}));setSelectedId(block.id);};
  const remove=(block:PortfolioBlock)=>{if(!window.confirm(`确定删除「${block.title}」区块吗？`))return;change(current=>({...current,document:{...current.document,blocks:current.document.blocks.filter(value=>value.id!==block.id)}}));setSelectedId('');};
  const runOptimize=async()=>{if(!item||!selected||!readyForServerAction())return;setWorking(true);setError('');try{const result=await optimizeBlock(item,selected,instruction);setProposal({blockId:selected.id,before:selected.data,beforeHash:contentHash(selected.data),after:result.data,explanation:result.explanation});}catch(error){setError(error instanceof Error?error.message:'优化失败');}finally{setWorking(false);}};
  const openSuggestion=(suggestion:ContentSuggestion)=>{setActiveSuggestion(suggestion);setUserFacts('');setTargetBlockId(blocks.find(block=>suggestion.recommendedBlockTypes.includes(block.type))?.id||blocks[0]?.id||'');setSyncLibrary(false);};
  const runSuggestion=async()=>{if(!item||!activeSuggestion||!userFacts.trim()||!readyForServerAction())return;const block=blocks.find(item=>item.id===targetBlockId);if(!block)return;setWorking(true);try{const result=await proposeSupplement(item,block,activeSuggestion,userFacts);setProposal({blockId:block.id,before:block.data,beforeHash:contentHash(block.data),after:result.data,explanation:result.explanation,suggestionId:activeSuggestion.id,userFacts,syncLibrary});setActiveSuggestion(null);}catch(error){setError(error instanceof Error?error.message:'补充失败');}finally{setWorking(false);}};
  const applyProposal=async()=>{if(!item||!proposal)return;const currentBlock=item.document.blocks.find(block=>block.id===proposal.blockId);if(!currentBlock||contentHash(currentBlock.data)!==proposal.beforeHash){setError('目标区块已发生变化，请重新生成修改建议。');setProposal(null);return;}changeBlock(proposal.blockId,{data:proposal.after});if(proposal.suggestionId)change(current=>({...current,contentSuggestions:current.contentSuggestions.map(value=>value.id===proposal.suggestionId?{...value,status:'applied'}:value)}));if(proposal.syncLibrary&&proposal.userFacts&&item.sourceResumeId){const source=loadResumes().find(value=>value.id===item.sourceResumeId&&value.type==='original');if(source){try{const suggestionTitle=item.contentSuggestions.find(value=>value.id===proposal.suggestionId)?.title||'补充经历';const experience=await formatFollowUpExperience(proposal.userFacts,suggestionTitle);await replaceResumeData(source.id,{...source.resume,experiences:[...source.resume.experiences,experience],skills:[...source.resume.skills,{id:generateId(),category:'补录',name:suggestionTitle,level:'熟悉',evidence:proposal.userFacts}]});}catch(error){setError(`主页已应用，但同步能力库失败：${error instanceof Error?error.message:'未知错误'}`);}}}setProposal(null);};
  const skipSuggestion=(id:string)=>change(current=>({...current,contentSuggestions:current.contentSuggestions.map(item=>item.id===id?{...item,status:'skipped'}:item)}));
  const publish=async()=>{if(!item||!readyForServerAction())return;try{const result=await publishPreparation(item.id);setItem({...item,status:'published',publicStatus:'published',publicSlug:result.slug,publishedAt:result.publishedAt});}catch(error){setError(error instanceof Error?error.message:'发布失败');}};
  const unpublish=async()=>{if(!item)return;try{await unpublishPreparation(item.id);setItem({...item,status:'draft',publicStatus:'unpublished'});}catch(error){setError(error instanceof Error?error.message:'下线失败');}};
  const useCloudVersion=async()=>{try{const latest=await getPreparation(id);setItem(latest);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);setError('');}catch(error){setError(error instanceof Error?error.message:'读取云端版本失败');}};
  const overwriteWithLocal=async()=>{if(!item)return;try{const latest=await getPreparation(id);const saved=await updatePreparation(latest,{document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,themeConfig:item.themeConfig});setItem(saved);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);setError('');}catch(error){setError(error instanceof Error?error.message:'恢复本机版本失败');}};
  if(loading)return <div className="page-shell text-sm text-ink-secondary">正在打开编辑器...</div>;if(!item)return <div className="page-shell"><p>{error||'求职准备不存在'}</p></div>;
  return <div className="prep-workspace animate-fade-in"><header className="prep-toolbar"><div><button onClick={()=>navigate('/preparations')} className="btn-link">← 我的求职准备</button><h1>{item.name}</h1><p>{item.mode==='targeted'?'针对岗位':'通用主页'} · 来源简历 V{item.sourceResumeVersion||'—'} · <span className={`save-${saveState}`}>{saveState==='saved'?'已保存':saveState==='saving'?'保存中…':saveState==='conflict'?'存在版本冲突':'离线待同步'}</span></p></div><div className="flex flex-wrap gap-2"><Link to={`/preparations/${item.id}/preview`} onClick={event=>{if(!readyForServerAction())event.preventDefault();}} className="btn-ghost">全屏预览</Link>{item.publicStatus==='published'?<><a href={`/p/${item.publicSlug}`} target="_blank" className="btn-ghost">查看公开页</a><button onClick={()=>void unpublish()} className="btn-ghost">下线</button><button onClick={()=>void publish()} className="btn-primary">更新发布</button></>:<button onClick={()=>void publish()} className="btn-primary">发布主页</button>}</div></header>
  <div className="prep-tabs"><Link className="active" to={`/preparations/${item.id}/home`}>求职主页</Link><Link to={`/preparations/${item.id}/interview`} onClick={event=>{if(!readyForServerAction())event.preventDefault();}}>面试准备 <small>私人</small></Link></div>
  {error&&<div className="mx-6 mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-terra-border bg-terra-light p-3 text-sm text-terra"><span>{error}</span>{saveState==='conflict'&&<span className="flex gap-2"><button className="btn-ghost h-8 px-3 text-xs" onClick={()=>void useCloudVersion()}>使用云端版本</button><button className="btn-primary h-8 px-3 text-xs" onClick={()=>void overwriteWithLocal()}>保留本机版本</button></span>}</div>}
  <div className="prep-grid"><aside className="prep-outline"><h2>页面区块</h2><button onClick={()=>setSelectedId('identity')} className={selectedId==='identity'?'active':''}>个人定位</button>{blocks.map((block,index)=><div key={block.id} className={`outline-row ${selected?.id===block.id?'active':''}`}><button onClick={()=>setSelectedId(block.id)}>{block.title}</button><span><button disabled={index===0} onClick={()=>move(block,-1)}>↑</button><button disabled={index===blocks.length-1} onClick={()=>move(block,1)}>↓</button></span></div>)}<select className="mt-3 w-full rounded border border-line bg-paper p-2 text-xs" value="" onChange={event=>event.target.value&&addBlock(event.target.value as PortfolioBlockType)}><option value="">＋ 添加区块</option>{blockTypes.map(type=><option key={type} value={type}>{blockNames[type]}</option>)}</select><h2 className="mt-8">内容完善建议</h2><div className="space-y-2">{item.contentSuggestions.filter(value=>value.status==='pending').map(suggestion=><article key={suggestion.id} className="suggestion-card"><strong>{suggestion.title}</strong><p>{suggestion.detail}</p><div><button onClick={()=>openSuggestion(suggestion)}>补充/优化</button><button onClick={()=>skipSuggestion(suggestion.id)}>暂时没有</button></div></article>)}{!item.contentSuggestions.some(value=>value.status==='pending')&&<p className="text-xs text-ink-weak">当前建议已处理完毕。</p>}</div></aside>
  <section className="prep-editor"><div className="card">{selectedId==='identity'||!selected?<IdentityEditor item={item} onChange={changeIdentity}/>:<><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{selected.type.toUpperCase()}</p><input className="input mt-2 text-xl font-semibold" value={selected.title} onChange={event=>changeBlock(selected.id,{title:event.target.value})}/></div><div className="flex gap-2"><button onClick={()=>changeBlock(selected.id,{visible:!selected.visible})} className="btn-ghost h-8 px-3 text-xs">{selected.visible?'隐藏':'显示'}</button><button onClick={()=>remove(selected)} className="h-8 px-2 text-xs text-ink-weak hover:text-terra">删除</button></div></div><BlockEditor block={selected} onData={data=>changeBlock(selected.id,{data})}/><div className="mt-6 border-t border-line pt-5"><label className="label">让 AI 只优化这个区块</label><textarea className="textarea h-20" value={instruction} onChange={event=>setInstruction(event.target.value)}/><button onClick={()=>void runOptimize()} disabled={working} className="btn-ghost mt-3">{working?'正在生成建议…':'生成局部优化建议'}</button></div></>}</div><ContactEditor item={item} onChange={document=>change(current=>({...current,document}))}/><div className="card mt-5 flex items-center justify-between"><div><h2 className="text-lg">主页内容准备好了？</h2><p className="mt-1 text-sm text-ink-secondary">下一步根据当前内容生成私人面试问题。</p></div><Link className="btn-primary" to={`/preparations/${item.id}/interview`} onClick={event=>{if(!readyForServerAction())event.preventDefault();}}>进入面试准备 →</Link></div></section>
  <aside className="prep-preview"><div className="theme-picker">{(Object.keys(themeNames) as ThemeId[]).map(theme=><button key={theme} className={item.themeId===theme?'active':''} onClick={()=>change(current=>({...current,themeId:theme}))}>{themeNames[theme]}</button>)}</div><div className="preview-frame"><PortfolioRenderer document={item.document} themeId={item.themeId} preview/></div></aside></div>
  {activeSuggestion&&<div className="modal-backdrop" onClick={()=>setActiveSuggestion(null)}><div className="modal max-w-2xl p-6" onClick={event=>event.stopPropagation()}><p className="eyebrow">CONTENT GUIDANCE</p><h2 className="mt-2 text-xl">{activeSuggestion.title}</h2><p className="mt-2 text-sm text-ink-secondary">只填写真实发生过的内容；AI 会先给出差异预览。</p><label className="mt-5 block"><span className="label">你的真实经历或补充信息</span><textarea className="textarea h-32" value={userFacts} onChange={event=>setUserFacts(event.target.value)} placeholder="用大白话描述背景、你的行动和真实结果…"/></label><label className="mt-4 block"><span className="label">加入哪个位置</span><select className="w-full rounded border border-line bg-paper p-2" value={targetBlockId} onChange={event=>setTargetBlockId(event.target.value)}>{blocks.filter(block=>activeSuggestion.recommendedBlockTypes.includes(block.type)).map(block=><option value={block.id} key={block.id}>{block.title}</option>)}</select></label>{loadResumes().some(value=>value.id===item.sourceResumeId&&value.type==='original')&&<label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={syncLibrary} onChange={event=>setSyncLibrary(event.target.checked)}/>同时把确认事实同步到能力库</label>}<div className="mt-6 flex justify-end gap-2"><button className="btn-ghost" onClick={()=>setActiveSuggestion(null)}>取消</button><button className="btn-primary" disabled={!userFacts.trim()||working} onClick={()=>void runSuggestion()}>生成修改建议</button></div></div></div>}
  {proposal&&<div className="modal-backdrop" onClick={()=>setProposal(null)}><div className="modal max-w-4xl p-6" onClick={event=>event.stopPropagation()}><p className="eyebrow">REVIEW CHANGES</p><h2 className="mt-2 text-xl">确认局部修改</h2><p className="mt-2 text-sm text-ink-secondary">{proposal.explanation}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Diff title="修改前" data={proposal.before}/><Diff title="修改后" data={proposal.after}/></div><div className="mt-6 flex justify-end gap-2"><button className="btn-ghost" onClick={()=>setProposal(null)}>不应用</button><button className="btn-primary" onClick={()=>void applyProposal()}>确认应用</button></div></div></div>}</div>;
};

const IdentityEditor:React.FC<{item:JobPreparation;onChange:(key:'name'|'headline'|'tagline'|'location',value:string)=>void}>=({item,onChange})=><><p className="eyebrow">HERO</p><h2 className="mt-2 text-xl">个人定位</h2>{(['name','headline','location'] as const).map(key=><label className="mt-4 block" key={key}><span className="label">{{name:'姓名',headline:'一句话定位',location:'所在地'}[key]}</span><input className="input" value={item.document.identity[key]||''} onChange={event=>onChange(key,event.target.value)}/></label>)}<label className="mt-4 block"><span className="label">价值主张</span><textarea className="textarea h-28" value={item.document.identity.tagline} onChange={event=>onChange('tagline',event.target.value)}/></label></>;

const BlockEditor:React.FC<{block:PortfolioBlock;onData:(data:Record<string,unknown>)=>void}>=({block,onData})=>{const data=block.data;if(block.type==='advantages')return <label className="mt-5 block"><span className="label">每行一项优势</span><textarea className="textarea h-48" value={arr(data.items).join('\n')} onChange={event=>onData({...data,items:event.target.value.split('\n').filter(Boolean)})}/></label>;if(block.type==='education')return <label className="mt-5 block"><span className="label">教育背景</span><textarea className="textarea h-32" value={String(data.content||'')} onChange={event=>onData({...data,content:event.target.value})}/></label>;if(block.type==='contact')return <div className="mt-5 space-y-4"><label><span className="label">标题</span><input className="input" value={String(data.heading||'')} onChange={event=>onData({...data,heading:event.target.value})}/></label><label><span className="label">说明</span><textarea className="textarea h-24" value={String(data.description||'')} onChange={event=>onData({...data,description:event.target.value})}/></label></div>;const key=data.items?'items':'groups';const items=arr(data[key]);const blank=block.type==='projects'?{name:'新项目',summary:'',results:[]}:block.type==='experience'?{company:'',role:'新经历',period:'',description:'',highlights:[]}:block.type==='skills'?{category:'能力分类',items:[]}:{name:'新条目'};return <div className="mt-5 space-y-4">{items.map((entry,index)=><article key={index} className="rounded-lg border border-line bg-canvas p-4">{Object.entries(entry||{}).filter(([field])=>field!=='sourceId').map(([field,val])=><label key={field} className="mb-3 block"><span className="label">{field}</span>{Array.isArray(val)?<textarea className="textarea h-20" value={val.join('\n')} onChange={event=>{const source=[...items];source[index]={...source[index],[field]:event.target.value.split('\n').filter(Boolean)};onData({...data,[key]:source})}}/>:<input className="input" value={String(val||'')} onChange={event=>{const source=[...items];source[index]={...source[index],[field]:event.target.value};onData({...data,[key]:source})}}/>}</label>)}<button className="text-xs text-ink-weak hover:text-terra" onClick={()=>onData({...data,[key]:items.filter((_,itemIndex)=>itemIndex!==index)})}>删除此条</button></article>)}<button className="btn-ghost h-8 px-3 text-xs" onClick={()=>onData({...data,[key]:[...items,blank]})}>＋ 添加一条</button></div>};

const ContactEditor:React.FC<{item:JobPreparation;onChange:(document:JobPreparation['document'])=>void}>=({item,onChange})=>{const doc=item.document;const add=()=>onChange({...doc,contacts:[...doc.contacts,{id:`contact_${Date.now()}`,kind:'website',label:'个人网站',value:'https://',public:false}]});return <div className="card mt-5"><div className="flex justify-between"><div><p className="eyebrow">PRIVACY</p><h2 className="mt-2 text-lg">公开联系方式与行动按钮</h2></div><button className="btn-ghost h-8 px-3 text-xs" onClick={add}>＋ 添加</button></div><p className="mt-2 text-xs text-ink-secondary">默认不会公开。发布前至少开启一项。</p><div className="mt-4 space-y-3">{doc.contacts.map(contact=><div key={contact.id} className="grid grid-cols-[auto_90px_100px_1fr] items-center gap-3"><input type="checkbox" checked={contact.public} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,public:event.target.checked}:value)})}/><select className="rounded border border-line bg-paper p-1 text-xs" value={contact.kind} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,kind:event.target.value as typeof contact.kind}:value)})}>{['email','phone','website','github','linkedin','wechat','custom'].map(kind=><option key={kind}>{kind}</option>)}</select><input className="input" value={contact.label} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,label:event.target.value}:value)})}/><input className="input" value={contact.value} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,value:event.target.value}:value)})}/></div>)}</div><label className="mt-5 block"><span className="label">主行动按钮</span><select className="w-full rounded border border-line bg-paper p-2" value={doc.primaryAction.contactId||''} onChange={event=>onChange({...doc,primaryAction:{label:'联系我',contactId:event.target.value||undefined}})}><option value="">请选择已公开的联系方式</option>{doc.contacts.filter(value=>value.public).map(contact=><option value={contact.id} key={contact.id}>{contact.label}</option>)}</select></label></div>};
const Diff:React.FC<{title:string;data:Record<string,unknown>}>=({title,data})=><div><h3 className="mb-2 text-sm font-medium">{title}</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-canvas p-4 text-xs leading-6">{JSON.stringify(data,null,2)}</pre></div>;
export default PreparationEditorView;
