import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import type {ContentSuggestion,JobPreparation,PortfolioBlock,PortfolioContact,ThemeId} from '../../types';
import PortfolioRenderer from '../PortfolioRenderer';
import {getPreparation,polishSuggestion,publishPreparation,themeNames,trackPreparationWrite,unpublishPreparation,updatePreparation} from '../../services/preparations';
import {contactKindLabels} from '../../utils/portfolioContacts';
import {preparationToCustomizedResume} from '../../utils/preparationResume';
import {saveCustomizedResume} from '../../utils/storage';

export const PreparationEditorView:React.FC=()=>{const{id=''}=useParams();const navigate=useNavigate();const[item,setItem]=useState<JobPreparation|null>(null);const[selectedId,setSelectedId]=useState('');const[loading,setLoading]=useState(true);const[dirty,setDirty]=useState(false);const[flushRequested,setFlushRequested]=useState(false);const[saveState,setSaveState]=useState<'saved'|'saving'|'offline'|'conflict'>('saved');const[error,setError]=useState('');const[working,setWorking]=useState(false);const[activeSuggestion,setActiveSuggestion]=useState<ContentSuggestion|null>(null);const[userFacts,setUserFacts]=useState('');const[polishedText,setPolishedText]=useState('');const[copied,setCopied]=useState(false);const loaded=useRef(false);const editVersion=useRef(0);
  const[suggestionsOpen,setSuggestionsOpen]=useState(false);const[contactsOpen,setContactsOpen]=useState(false);const[publishOpen,setPublishOpen]=useState(false);const[publishName,setPublishName]=useState('');const[publishing,setPublishing]=useState(false);
  const recoveryKey=`wf_preparation_draft:${localStorage.getItem('wf_cloud_user_id')||'local'}:${id}`;
  useEffect(()=>{getPreparation(id).then(value=>{setError('');const recovery=localStorage.getItem(recoveryKey);let next=value;if(recovery){try{const parsed=JSON.parse(recovery);if(parsed.revision===value.revision&&parsed.savedAt>value.updatedAt)next={...value,document:parsed.document,contentSuggestions:parsed.contentSuggestions,themeId:parsed.themeId};else if(parsed.revision!==value.revision){next={...value,document:parsed.document,contentSuggestions:parsed.contentSuggestions,themeId:parsed.themeId};setSaveState('conflict');setError('发现未同步的本机草稿和更新的云端版本，请选择要保留的版本。');}}catch{/* ignore */}}setItem(next);setSelectedId('identity');loaded.current=true;}).catch(err=>setError(err instanceof Error?err.message:'读取失败')).finally(()=>setLoading(false));},[id,recoveryKey]);
  useEffect(()=>{if(!item||!dirty||!loaded.current)return;localStorage.setItem(recoveryKey,JSON.stringify({revision:item.revision,document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,savedAt:new Date().toISOString()}));const timer=window.setTimeout(async()=>{const savingVersion=editVersion.current;setSaveState('saving');setFlushRequested(false);try{const saved=await trackPreparationWrite(updatePreparation(item,{document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,themeConfig:item.themeConfig}));setError(current=>current==='读取求职准备失败'||current==='保存求职准备失败'?'' : current);if(editVersion.current===savingVersion){setItem(saved);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);}else{setItem(current=>current?{...current,revision:saved.revision,updatedAt:saved.updatedAt}:current);setSaveState('saving');}}catch(error){const message=error instanceof Error?error.message:'';setSaveState(message.includes('其他页面')?'conflict':'offline');setError(message||'保存失败');}},flushRequested?0:800);return()=>window.clearTimeout(timer);},[dirty,item,recoveryKey,flushRequested]);
  useEffect(()=>{const flush=()=>setFlushRequested(true);window.addEventListener('wf-flush-preparations',flush);return()=>window.removeEventListener('wf-flush-preparations',flush);},[]);
  const modalVisible=suggestionsOpen||contactsOpen||publishOpen||Boolean(activeSuggestion);
  useEffect(()=>{if(!modalVisible)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[modalVisible]);
  const blocks=useMemo(()=>[...(item?.document.blocks||[])].sort((a,b)=>a.order-b.order),[item]);
  const selectSection=(sectionId:string,scroll=false)=>{setSelectedId(sectionId);if(scroll)window.requestAnimationFrame(()=>document.querySelector(`[data-section-id="${sectionId}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}));};
  const change=(mutate:(draft:JobPreparation)=>JobPreparation)=>{editVersion.current+=1;setItem(current=>current?mutate(current):current);setDirty(true);};
  const changeBlock=(id:string,updates:Partial<PortfolioBlock>)=>change(current=>({...current,document:{...current.document,blocks:current.document.blocks.map(block=>block.id===id?{...block,...updates}:block)}}));
  const readyForServerAction=()=>{if(dirty||saveState!=='saved'){setError('请等待当前草稿保存完成后再继续。');return false;}return true;};
  const move=(block:PortfolioBlock,delta:number)=>{const sorted=[...blocks];const index=sorted.findIndex(item=>item.id===block.id);const other=sorted[index+delta];if(!other)return;changeBlock(block.id,{order:other.order});changeBlock(other.id,{order:block.order});};
  const openSuggestion=(suggestion:ContentSuggestion)=>{setSuggestionsOpen(false);setActiveSuggestion(suggestion);setUserFacts('');setPolishedText('');setCopied(false);};
  const runSuggestion=async()=>{if(!item||!activeSuggestion||!userFacts.trim())return;setWorking(true);setCopied(false);setError('');try{const result=await polishSuggestion(item,activeSuggestion,userFacts.trim());setPolishedText(result.text);}catch(error){setError(error instanceof Error?error.message:'润色失败');}finally{setWorking(false);}};
  const copyPolished=async()=>{if(!polishedText)return;try{await navigator.clipboard.writeText(polishedText);setCopied(true);}catch{setError('复制失败，请手动选择润色结果复制。');}};
  const finishSuggestion=()=>{if(!activeSuggestion)return;change(current=>({...current,contentSuggestions:current.contentSuggestions.map(value=>value.id===activeSuggestion.id?{...value,status:'applied'}:value)}));setActiveSuggestion(null);};
  const skipSuggestion=(id:string)=>change(current=>({...current,contentSuggestions:current.contentSuggestions.map(item=>item.id===id?{...item,status:'skipped'}:item)}));
  const openPublish=()=>{if(!item||!readyForServerAction())return;setPublishName(item.name);setPublishOpen(true);};
  const publish=async()=>{if(!item||!publishName.trim()||publishing)return;setPublishing(true);setError('');try{const result=await publishPreparation(item.id);saveCustomizedResume(preparationToCustomizedResume(item),{name:publishName.trim(),sourceIds:item.sourceResumeId?[item.sourceResumeId]:[],targetJob:{position:item.careerDirection,company:item.jobSnapshot?.company,matchScore:typeof item.matchResultSnapshot?.score==='number'?item.matchResultSnapshot.score:null,jobId:item.id}});setItem({...item,status:'published',publicStatus:'published',publicSlug:result.slug,publishedAt:result.publishedAt});setPublishOpen(false);}catch(error){setError(error instanceof Error?error.message:'发布失败');}finally{setPublishing(false);}};
  const unpublish=async()=>{if(!item)return;try{await unpublishPreparation(item.id);setItem({...item,status:'draft',publicStatus:'unpublished'});}catch(error){setError(error instanceof Error?error.message:'下线失败');}};
  const useCloudVersion=async()=>{try{const latest=await getPreparation(id);setItem(latest);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);setError('');}catch(error){setError(error instanceof Error?error.message:'读取云端版本失败');}};
  const overwriteWithLocal=async()=>{if(!item)return;try{const latest=await getPreparation(id);const saved=await updatePreparation(latest,{document:item.document,contentSuggestions:item.contentSuggestions,themeId:item.themeId,themeConfig:item.themeConfig});setItem(saved);setDirty(false);setSaveState('saved');localStorage.removeItem(recoveryKey);setError('');}catch(error){setError(error instanceof Error?error.message:'恢复本机版本失败');}};
  if(loading)return <div className="page-shell text-sm text-ink-secondary">正在打开编辑器...</div>;if(!item)return <div className="page-shell"><p>{error||'求职准备不存在'}</p></div>;
  const pendingSuggestions=(Array.isArray(item.contentSuggestions)?item.contentSuggestions:[]).filter(value=>value.status==='pending');
  return <div className="prep-workspace animate-fade-in"><header className="prep-toolbar"><div><button onClick={()=>navigate('/preparations')} className="btn-link">← 我的求职准备</button><h1>{item.name}</h1><p>{item.mode==='targeted'?'针对岗位':'通用主页'} · 来源简历 V{item.sourceResumeVersion||'—'} · <span className={`save-${saveState}`}>{saveState==='saved'?'已保存':saveState==='saving'?'保存中…':saveState==='conflict'?'存在版本冲突':'离线待同步'}</span></p></div><div className="flex flex-wrap gap-2"><label className="theme-select"><span>主题</span><select value={item.themeId} onChange={event=>change(current=>({...current,themeId:event.target.value as ThemeId}))}>{(Object.keys(themeNames) as ThemeId[]).map(theme=><option key={theme} value={theme}>{themeNames[theme]}</option>)}</select></label><Link to={`/preparations/${item.id}/preview`} onClick={event=>{if(!readyForServerAction())event.preventDefault();}} className="btn-ghost">全屏预览</Link>{item.publicStatus==='published'?<><a href={`/p/${item.publicSlug}`} target="_blank" className="btn-ghost">查看公开页</a><button onClick={()=>void unpublish()} className="btn-ghost">下线</button><button onClick={openPublish} className="btn-primary">更新发布</button></>:<button onClick={openPublish} className="btn-primary">发布主页</button>}</div></header>
  <div className="prep-tabs"><Link className="active" to={`/preparations/${item.id}/home`}>求职主页</Link><Link to={`/preparations/${item.id}/interview`} onClick={event=>{if(!readyForServerAction())event.preventDefault();}}>面试准备 <small>私人</small></Link></div>
  {error&&<div className="mx-6 mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-terra-border bg-terra-light p-3 text-sm text-terra"><span>{error}</span>{saveState==='conflict'&&<span className="flex gap-2"><button className="btn-ghost h-8 px-3 text-xs" onClick={()=>void useCloudVersion()}>使用云端版本</button><button className="btn-primary h-8 px-3 text-xs" onClick={()=>void overwriteWithLocal()}>保留本机版本</button></span>}</div>}
  <div className="prep-grid"><aside className="prep-outline"><h2>页面区块</h2><button onClick={()=>selectSection('identity',true)} className={selectedId==='identity'?'active':''}><span>个人定位</span></button>{blocks.map((block,index)=><div key={block.id} className={`outline-row ${selectedId===block.id?'active':''} ${block.visible?'':'is-hidden'}`}><button onClick={()=>selectSection(block.id,true)}>{block.title}</button><span className="outline-actions"><button type="button" title="上移" disabled={index===0} onClick={()=>move(block,-1)}>↑</button><button type="button" title="下移" disabled={index===blocks.length-1} onClick={()=>move(block,1)}>↓</button><button type="button" title={block.visible?'隐藏区块':'显示区块'} onClick={()=>changeBlock(block.id,{visible:!block.visible})}>{block.visible?'◉':'○'}</button></span></div>)}<div className="outline-utilities"><button type="button" onClick={()=>setSuggestionsOpen(true)}><span>内容建议</span>{pendingSuggestions.length>0&&<b>{pendingSuggestions.length}</b>}</button><button type="button" onClick={()=>setContactsOpen(true)}><span>联系方式与隐私</span><span>›</span></button></div></aside>
  <section className="prep-live-editor"><div className="editable-preview-frame"><PortfolioRenderer document={item.document} themeId={item.themeId} editable onSectionSelect={sectionId=>selectSection(sectionId)} onDocumentChange={document=>change(current=>({...current,document}))}/></div></section></div>
  {suggestionsOpen&&<div className="modal-backdrop" onClick={()=>setSuggestionsOpen(false)}><div className="modal modal-scroll max-w-2xl p-6" onClick={event=>event.stopPropagation()}><p className="eyebrow">CONTENT GUIDANCE</p><h2 className="mt-2 text-xl">内容完善建议</h2><p className="mt-2 text-sm text-ink-secondary">选择一项后输入真实情况，AI 只负责润色，不会自动修改主页。</p><div className="mt-5 space-y-3">{pendingSuggestions.map(suggestion=><article key={suggestion.id} className="suggestion-card"><strong>{suggestion.title}</strong><p>{suggestion.detail}</p><div><button onClick={()=>openSuggestion(suggestion)}>填写并润色</button><button onClick={()=>skipSuggestion(suggestion.id)}>暂时没有</button></div></article>)}{pendingSuggestions.length===0&&<p className="rounded-lg bg-canvas p-5 text-sm text-ink-secondary">当前建议已处理完毕。</p>}</div><div className="mt-6 flex justify-end"><button className="btn-ghost" onClick={()=>setSuggestionsOpen(false)}>关闭</button></div></div></div>}
  {contactsOpen&&<div className="modal-backdrop" onClick={()=>setContactsOpen(false)}><div className="modal modal-scroll max-w-4xl p-6" onClick={event=>event.stopPropagation()}><ContactEditor item={item} onChange={document=>change(current=>({...current,document}))}/><div className="mt-5 flex justify-end"><button className="btn-primary" onClick={()=>setContactsOpen(false)}>完成</button></div></div></div>}
  {publishOpen&&<div className="modal-backdrop" onClick={()=>!publishing&&setPublishOpen(false)}><div className="modal max-w-lg p-6" onClick={event=>event.stopPropagation()}><p className="eyebrow">PUBLISH & SAVE</p><h2 className="mt-2 text-xl">命名定制简历</h2><p className="mt-2 text-sm text-ink-secondary">发布主页后，当前主页内容会同时保存到“简历与能力库”的定制简历中。</p><label className="mt-5 block"><span className="label">定制简历名称</span><input className="input" autoFocus maxLength={120} value={publishName} onChange={event=>setPublishName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&publishName.trim())void publish();}} placeholder="例如：AI 产品经理 @ 目标公司"/></label><div className="mt-6 flex justify-end gap-2"><button className="btn-ghost" disabled={publishing} onClick={()=>setPublishOpen(false)}>取消</button><button className="btn-primary" disabled={!publishName.trim()||publishing} onClick={()=>void publish()}>{publishing?'正在发布…':'确认发布'}</button></div></div></div>}
  {activeSuggestion&&<div className="modal-backdrop" onClick={()=>setActiveSuggestion(null)}><div className="modal modal-scroll max-w-2xl p-6" onClick={event=>event.stopPropagation()}><p className="eyebrow">CONTENT GUIDANCE</p><h2 className="mt-2 text-xl">{activeSuggestion.title}</h2><p className="mt-2 text-sm text-ink-secondary">{activeSuggestion.detail}</p><label className="mt-5 block"><span className="label">你的真实经历或补充信息</span><textarea className="textarea h-36" value={userFacts} onChange={event=>setUserFacts(event.target.value)} placeholder="用大白话描述真实背景、行动和结果…"/></label>{polishedText&&<label className="mt-5 block"><span className="label">AI 润色结果（可继续修改）</span><textarea className="textarea h-40" value={polishedText} onChange={event=>{setPolishedText(event.target.value);setCopied(false);}}/></label>}<div className="mt-6 flex flex-wrap justify-end gap-2"><button className="btn-ghost" onClick={()=>setActiveSuggestion(null)}>取消</button>{polishedText&&<button className="btn-ghost" onClick={finishSuggestion}>标记已处理</button>}<button className="btn-ghost" disabled={!polishedText} onClick={()=>void copyPolished()}>{copied?'已复制':'复制结果'}</button><button className="btn-primary" disabled={!userFacts.trim()||working} onClick={()=>void runSuggestion()}>{working?'正在润色…':polishedText?'重新润色':'AI 润色'}</button></div></div></div>}</div>;
};

const ContactEditor:React.FC<{item:JobPreparation;onChange:(document:JobPreparation['document'])=>void}>=({item,onChange})=>{const doc=item.document;const kinds=Object.keys(contactKindLabels) as PortfolioContact['kind'][];const add=()=>onChange({...doc,contacts:[...doc.contacts,{id:`contact_${Date.now()}`,kind:'website',label:contactKindLabels.website,value:'https://',public:false}]});const changeKind=(contactId:string,kind:PortfolioContact['kind'])=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contactId?{...value,kind,label:contactKindLabels[kind]}:value)});return <div className="card mt-5"><div className="flex justify-between"><div><p className="eyebrow">PRIVACY</p><h2 className="mt-2 text-lg">公开联系方式与行动按钮</h2></div><button className="btn-ghost h-8 px-3 text-xs" onClick={add}>＋ 添加</button></div><p className="mt-2 text-xs text-ink-secondary">默认不会公开。发布前至少开启一项。</p><div className="mt-4 space-y-3">{doc.contacts.map(contact=><div key={contact.id} className="grid grid-cols-[auto_90px_100px_1fr] items-center gap-3"><input type="checkbox" checked={contact.public} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,public:event.target.checked}:value)})}/><select className="rounded border border-line bg-paper p-1 text-xs" value={contact.kind} onChange={event=>changeKind(contact.id,event.target.value as PortfolioContact['kind'])}>{kinds.map(kind=><option key={kind} value={kind}>{kind}</option>)}</select><input className="input" aria-label="联系方式中文名称" value={contact.label} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,label:event.target.value}:value)})}/><input className="input" value={contact.value} onChange={event=>onChange({...doc,contacts:doc.contacts.map(value=>value.id===contact.id?{...value,value:event.target.value}:value)})}/></div>)}</div><label className="mt-5 block"><span className="label">主行动按钮</span><select className="w-full rounded border border-line bg-paper p-2" value={doc.primaryAction.contactId||''} onChange={event=>onChange({...doc,primaryAction:{label:'联系我',contactId:event.target.value||undefined}})}><option value="">请选择已公开的联系方式</option>{doc.contacts.filter(value=>value.public).map(contact=><option value={contact.id} key={contact.id}>{contact.label}</option>)}</select></label></div>};
export default PreparationEditorView;
