import React,{useEffect,useRef} from 'react';
import type { PortfolioBlock, PortfolioContact, PortfolioDocument, ThemeId } from '../types';
import './portfolio.css';

const array=(value:unknown):any[]=>Array.isArray(value)?value:[];
const value=(input:unknown)=>typeof input==='string'?input:'';

const EditableText:React.FC<{text:string;onCommit?:(text:string)=>void;className?:string;as?:'span'|'p'|'h1'|'h2'|'h3'|'h4'|'strong'|'small';multiline?:boolean}>=({text,onCommit,className,as='span',multiline=false})=>{const ref=useRef<HTMLElement|null>(null);useEffect(()=>{if(ref.current&&document.activeElement!==ref.current)ref.current.innerText=text;},[text]);const Tag=as;return <Tag ref={ref as never} className={`${className||''}${onCommit?' pf-editable':''}`} contentEditable={Boolean(onCommit)} suppressContentEditableWarning spellCheck={false} title={onCommit?'点击编辑文字':undefined} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.currentTarget.innerText=text;event.currentTarget.blur();}else if(event.key==='Enter'&&!multiline){event.preventDefault();event.currentTarget.blur();}}} onBlur={event=>{if(!onCommit)return;const next=event.currentTarget.innerText.replace(/\u00a0/g,' ').trim();if(next!==text)onCommit(next);else event.currentTarget.innerText=text;}}>{text}</Tag>};

function contactHref(contact?:PortfolioContact):string|undefined{
  if(!contact)return undefined;
  if(contact.kind==='email')return `mailto:${contact.value}`;
  if(contact.kind==='phone')return `tel:${contact.value}`;
  if(['website','github','linkedin'].includes(contact.kind)&&/^https?:\/\//i.test(contact.value))return contact.value;
  return '#contact';
}

const BlockView:React.FC<{block:PortfolioBlock;editable?:boolean;onChange?:(updates:Partial<PortfolioBlock>)=>void;onSelect?:()=>void}>=({block,editable=false,onChange,onSelect})=>{
  const data=block.data;
  const setData=(updates:Record<string,unknown>)=>onChange?.({data:{...data,...updates}});const updateItem=(key:'items'|'groups',index:number,updates:Record<string,unknown>)=>{const items=[...array(data[key])];items[index]={...items[index],...updates};setData({[key]:items});};const sectionProps=editable?{onClick:onSelect,'data-section-id':block.id}:{};const title=<EditableText as="h2" text={block.title} onCommit={editable?text=>onChange?.({title:text}):undefined}/>;
  if(block.type==='advantages')return <section className="pf-section" {...sectionProps}><p className="pf-kicker">WHAT I BRING</p>{title}<div className="pf-advantages">{array(data.items).map((item,index)=><article key={index}><span>{String(index+1).padStart(2,'0')}</span><EditableText as="p" text={value(item)} multiline onCommit={editable?text=>{const items=[...array(data.items)];items[index]=text;setData({items});}:undefined}/></article>)}</div></section>;
  if(block.type==='projects')return <section className="pf-section" {...sectionProps}><p className="pf-kicker">SELECTED WORK</p>{title}<div className="pf-projects">{array(data.items).map((item,index)=><article key={index}><div><small>CASE {String(index+1).padStart(2,'0')}</small><EditableText as="h3" text={value(item.name)} onCommit={editable?text=>updateItem('items',index,{name:text}):undefined}/></div><EditableText as="p" text={value(item.summary)} multiline onCommit={editable?text=>updateItem('items',index,{summary:text}):undefined}/>{array(item.results).length>0&&<ul>{array(item.results).map((result,i)=><li key={i}><EditableText text={value(result)} multiline onCommit={editable?text=>{const results=[...array(item.results)];results[i]=text;updateItem('items',index,{results});}:undefined}/></li>)}</ul>}</article>)}</div></section>;
  if(block.type==='experience')return <section className="pf-section" {...sectionProps}><p className="pf-kicker">EXPERIENCE</p>{title}<div className="pf-timeline">{array(data.items).map((item,index)=><article key={index}><EditableText as="p" className="pf-period" text={value(item.period)} onCommit={editable?text=>updateItem('items',index,{period:text}):undefined}/><div><EditableText as="h3" text={value(item.role)} onCommit={editable?text=>updateItem('items',index,{role:text}):undefined}/><EditableText as="h4" text={value(item.company)} onCommit={editable?text=>updateItem('items',index,{company:text}):undefined}/><EditableText as="p" text={value(item.description)} multiline onCommit={editable?text=>updateItem('items',index,{description:text}):undefined}/>{array(item.highlights||item.achievements).length>0&&<ul>{array(item.highlights||item.achievements).map((point,i)=><li key={i}><EditableText text={value(point)} multiline onCommit={editable?text=>{const highlights=[...array(item.highlights||item.achievements)];highlights[i]=text;updateItem('items',index,{highlights});}:undefined}/></li>)}</ul>}</div></article>)}</div></section>;
  if(block.type==='skills')return <section className="pf-section" {...sectionProps}><p className="pf-kicker">CAPABILITIES</p>{title}<div className="pf-skills">{array(data.groups).map((group,index)=><article key={index}><EditableText as="h3" text={value(group.category)||'专业能力'} onCommit={editable?text=>updateItem('groups',index,{category:text}):undefined}/><div>{array(group.items).map((skill,i)=><EditableText key={i} text={value(skill)} onCommit={editable?text=>{const items=[...array(group.items)];items[i]=text;updateItem('groups',index,{items});}:undefined}/>)}</div></article>)}</div></section>;
  if(block.type==='education')return <section className="pf-section pf-education" {...sectionProps}><p className="pf-kicker">EDUCATION</p>{title}<EditableText as="p" text={value(data.content)} multiline onCommit={editable?text=>setData({content:text}):undefined}/></section>;
  if(block.type==='contact')return <section className="pf-section pf-contact" {...sectionProps}><p className="pf-kicker">LET'S TALK</p><EditableText as="h2" text={value(data.heading)||block.title} onCommit={editable?text=>setData({heading:text}):undefined}/><EditableText as="p" text={value(data.description)} multiline onCommit={editable?text=>setData({description:text}):undefined}/></section>;
  return null;
};

export const PortfolioRenderer:React.FC<{document:PortfolioDocument;themeId:ThemeId;preview?:boolean;editable?:boolean;onDocumentChange?:(document:PortfolioDocument)=>void;onSectionSelect?:(id:string)=>void}>=({document,themeId,preview=false,editable=false,onDocumentChange,onSectionSelect})=>{
  const contacts=(document.contacts||[]).filter(item=>item.public);
  const setIdentity=(key:keyof PortfolioDocument['identity'],text:string)=>onDocumentChange?.({...document,identity:{...document.identity,[key]:text}});const setBlock=(id:string,updates:Partial<PortfolioBlock>)=>onDocumentChange?.({...document,blocks:document.blocks.map(block=>block.id===id?{...block,...updates}:block)});
  return <main className={`portfolio theme-${themeId}${preview?' is-preview':''}${editable?' is-editable':''}`}>
    <header className="pf-hero" data-section-id={editable?'identity':undefined} onClick={editable?()=>onSectionSelect?.('identity'):undefined}><p className="pf-kicker">HELLO, I'M</p><EditableText as="h1" text={document.identity.name} onCommit={editable?text=>setIdentity('name',text):undefined}/><EditableText as="p" className="pf-headline" text={document.identity.headline} multiline onCommit={editable?text=>setIdentity('headline',text):undefined}/><EditableText as="p" className="pf-tagline" text={document.identity.tagline} multiline onCommit={editable?text=>setIdentity('tagline',text):undefined}/>{document.identity.location&&<div className="pf-hero-meta"><EditableText text={document.identity.location} onCommit={editable?text=>setIdentity('location',text):undefined}/></div>}</header>
    <div className="pf-body">{[...(document.blocks||[])].filter(block=>block.visible&&block.type!=='hero').sort((a,b)=>a.order-b.order).map(block=><BlockView key={block.id} block={block} editable={editable} onChange={updates=>setBlock(block.id,updates)} onSelect={()=>onSectionSelect?.(block.id)}/>)}</div>
    {contacts.length>0&&<footer id="contact" className="pf-footer"><div className="pf-contact-grid">{contacts.map(contact=>{const contactLink=contactHref(contact);const content=<><span className="pf-contact-label">{contact.label}</span><span className="pf-contact-value">{contact.value}</span></>;return contactLink&&contactLink!=='#contact'?<a className="pf-contact-item" key={contact.id} href={contactLink} target={contactLink.startsWith('http')?'_blank':undefined} rel="noreferrer">{content}</a>:<div className="pf-contact-item" key={contact.id}>{content}</div>;})}</div></footer>}
  </main>;
};

export default PortfolioRenderer;
